# Generated by Django 3.2.8 on 2021-11-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211108_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomuser',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ecomuser',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
