# Generated by Django 3.2.8 on 2021-11-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211110_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ecomuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ecomuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='ecomuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
