# Generated by Django 3.2.8 on 2021-11-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211110_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_empty',
            field=models.BooleanField(default=True),
        ),
    ]
