# Generated by Django 3.2.8 on 2021-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211115_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'Confirmed'), ('T', 'In Transit'), ('D', 'Delivered'), ('X', 'Cancelled')], default='C', max_length=1),
        ),
    ]
