# Generated by Django 3.2.8 on 2021-11-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211116_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
