# Generated by Django 3.2.8 on 2021-11-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_verified_buyer',
        ),
    ]
